# application.yml ??

spring:
  profiles:
    active: local  # ?? ????? ???
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL ???? ???
  h2:
    console:
      enabled: false  # H2 ?? ????
  jpa:
    hibernate:
      ddl-auto: update  # 애플리케이션 재시작 시 테이블을 생성하거나 업데이트함
    show-sql: true  # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate.format_sql: true  # SQL ??? ???
      hibernate.dialect: org.hibernate.dialect.MySQLDialect  # MySQL ??

  springdoc:
    paths-to-exclude: /swagger-resources/**, /v3/**, /v2/**
    swagger-ui:
      operationsSorter: method
    api-docs:
      path: /v3/api-docs/swagger-config