# application.yml ??

spring:
  profiles:
    active: local  # ?? ????? ???

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true  # SQL ??? ???
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL ??
  redis:
    host: localhost
    port: 6379

  springdoc:
    paths-to-exclude: /swagger-resources/**, /v3/**, /v2/**
    swagger-ui:
      operationsSorter: method
    api-docs:
      path: /v3/api-docs/swagger-config

  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql:
                BasicBinder: TRACE